import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
const orig=root+'reference/original/';
const read=p=>fs.readFileSync(p,'utf8');
function block(s,start){let i=s.indexOf('{',start),depth=0,q=null,line=false,comment=false;for(let j=i;j<s.length;j++){let c=s[j],n=s[j+1];if(line){if(c==='\n')line=false;continue}if(comment){if(c==='*'&&n==='/'){comment=false;j++}continue}if(q){if(c==='\\'){j++;continue}if(c===q)q=null;continue}if(c==='/'&&n==='/'){line=true;j++;continue}if(c==='/'&&n==='*'){comment=true;j++;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')depth++;if(c==='}'&&--depth===0)return s.slice(start,j+1)}throw Error('unclosed block')}
function fn(s,name){const start=s.indexOf('function '+name+'(');if(start<0)throw Error(name);return block(s,start)}
function ctx(code){return vm.runInNewContext(code+'\n;new Proxy({}, {get:(_,k)=>eval(k)})',{}, {timeout:20000})}
function ts(files){return ctx(files.map(f=>stripTypeScriptTypes(read(root+'src/engineering/'+f),{mode:'strip'}).replace(/^import[\s\S]*?;\s*/gm,'').replace(/\bexport\s+/g,'')).join('\n'))}
const published=JSON.parse(read(root+'public/data/workspace.json'));const referenceRows=id=>published.resources.find(r=>r.key===id).data.rows;
const results=[];let checks=0;function eq(a,b,path=''){checks++; if(typeof a==='number'&&typeof b==='number'){if(Object.is(a,b)||Math.abs(a-b)<=1e-9*Math.max(1,Math.abs(a),Math.abs(b)))return;throw Error(`${path}: ${a} != ${b}`)}if(a===null||b===null||typeof a!=='object'||typeof b!=='object'){if(a!==b)throw Error(`${path}: ${a} != ${b}`);return}for(const k of Object.keys(a)){if(!(k in b))throw Error(`${path}.${k} missing`);eq(a[k],b[k],path+'.'+k)}}
function test(name,f){const before=checks;try{const detail=f();results.push({name,status:detail?.unequalBandSteps?'CONFIRMED_DIFFERENCE':'PASS',comparisons:checks-before,detail})}catch(e){results.push({name,status:'DIFFERENCE_OR_HARNESS_ERROR',comparisons:checks-before,error:String(e)})}}
test('Blower pure power, pressure and efficiency functions',()=>{const s=read(orig+'air-blower.html');const o=ctx(['shaftPowerKw','normalizePressures','fluidPowerKw','isentropicEff','polytropicEff','detectActiveBlower'].map(n=>fn(s,n)).join('\n'));const n=ts(['blower/calculations.ts']);for(const p of [[283.15,390,0.93,2,1.4],[277,277,1,1,1.4],[300,410,1,3,1.3],[300,280,1,2,1.4]]){eq(o.isentropicEff(...p),n.isentropicEfficiency(...p));eq(o.polytropicEff(...p),n.polytropicEfficiency(...p))}for(const i of [0,5,100,117])eq(o.shaftPowerKw(4000,i,.85),n.shaftPowerKw(4000,i,.85));eq(o.normalizePressures(93,105,.93),n.normalizePressures(93,105,.93));eq(o.fluidPowerKw(20000,.9),n.fluidPowerKw(20000,.9));return 'Representative normal and edge inputs; batch parsing/forward-fill not included.'});
test('Heater all current demo rows plus missing/zero-input cases',()=>{const s=read(orig+'fired-heater.html');const o=ctx(s.split('\n').slice(768,831).join('\n')+'\n'+['getFuelComposition','stoichO2KgPerKgFuel','stoichAirKgPerKgFuel','h2oKgPerKgFuel','combustionMassFlows','calcRow'].map(n=>fn(s,n)).join('\n'));const n=ts(['heater/fuelData.ts','heater/calculations.ts','heater/demoData.ts']);const map={fuelFlowKgS:'mf',combustionAirTempC:'Tca',stackTempC:'Ts',fuelTempC:'Tf',processFlowKgS:'mp',processInC:'Tp_in',processOutC:'Tp_out',processCpKjKgK:'cp_p',stackO2Pct:'o2',bridgewallAC:'bw_a',bridgewallBC:'bw_b',fuelCaseOverride:'fuel'};const out={bridgewallAvgC:'bw_avg',excessAirPct:'ea_pct',etaHeatBalancePct:'eta_hb',etaPtc4Pct:'eta_ptc4',etaProcessPct:'eta_p',etaDeltaPp:'eta_delta',qLhvKw:'q_lhv',qAbsorbedKw:'q_abs',qProcessKw:'q_p',qFuelSensibleKw:'q_f',qCombustionAirKw:'q_ca',qStackKw:'q_s',qRadiationLossKw:'q_hl',qInKw:'q_in',combustionAirKgS:'m_ca',stackMassKgS:'m_s',airFuelRatio:'af_ratio',dryLossPct:'loss_dry',moistureLossPct:'loss_moist',radiationLossPct:'loss_rad',unaccountedLossPct:'loss_unacc',closurePct:'closure_pct'};const rows=[...referenceRows('fired-heater'),...[null,0].map(v=>({...n.HEATER_DEMO_DATA[0],fuelFlowKgS:v})),{...n.HEATER_DEMO_DATA[0],stackO2Pct:null}];for(const r of rows){const old={timestamp:r.timestamp,...Object.fromEntries(Object.entries(map).map(([k,v])=>[v,r[k]]))};const a=o.calcRow(old,{fuelCase:n.DEFAULT_HEATER_CONFIG.fuelCase,radLoss:1.5,unacc:.5,tref:15});const b=n.calcHeaterRow(r,n.DEFAULT_HEATER_CONFIG);for(const[k,v]of Object.entries(out))eq(a[v],b[k],k)}return `${rows.length} rows, 22 derived outputs per row.`});
test('Exchanger all demo rows, crossover, missing inputs and F edge cases',()=>{const s=read(orig+'shell-tube-exchanger.html');const o=ctx('const EPSILON=1e-9;'+fn(s,'calcF')+fn(s,'calcRow'));const n=ts(['exchanger/calculations.ts','exchanger/demoData.ts']);for(const p of [[.3,1,2],[.4,.8,2],[1,.5,2],[.2,2,0],[.6,1,1]])eq(o.calcF(...p),n.lmtdCorrectionF(...p));const map={hotInC:'t_hot_in_c',hotOutC:'t_hot_out_c',coldInC:'t_cold_in_c',coldOutC:'t_cold_out_c',hotFlowKgHr:'m_hot_kghr',hotCpKjKgK:'cp_hot',coldFlowKgHr:'m_cold_kghr',coldCpKjKgK:'cp_cold'};const out={qHotKw:'Q_hot_kw',qColdKw:'Q_cold_kw',qAvgKw:'Q_avg_kw',qAvgMw:'Q_avg_MW',imbalancePct:'imbalance_pct',lmtdC:'LMTD_c',lmtdEffC:'LMTD_eff_c',pRatio:'P_ratio',rRatio:'R_ratio',fFactor:'F_factor',uDirtyWm2k:'U_dirty',rfE4:'Rf_e4',effectivenessPct:'eff_pct',approachHotC:'approach_hot',approachColdC:'approach_cold',dutyDeviationPct:'duty_dev_pct',crossover:'crossover'};const rows=[...referenceRows('shell-tube-exchanger'),{...n.EXCHANGER_DEMO_DATA[0],hotInC:null},{...n.EXCHANGER_DEMO_DATA[0],coldOutC:190}];for(const r of rows){const a=o.calcRow(Object.fromEntries(Object.entries(map).map(([k,v])=>[v,r[k]])),{nShell:2,area:124.8,uClean:500,designQ_MW:3.5});const b=n.calcExchangerRow(r,n.DEFAULT_EXCHANGER_CONFIG);for(const[k,v]of Object.entries(out))eq(a[v],b[k],k)}return `${rows.length} rows, 17 derived outputs; five F cases.`});
test('Membrane original batch versus current row engine',()=>{const s=read(orig+'membrane-analyzer.html');const o=ctx(fn(s,'synthesizeOnlineFeedH2')+fn(s,'processBatch'));const n=ts(['membrane/calculations.ts','membrane/demoData.ts']);const rows=[...referenceRows('membrane-analyzer'),{...n.MEMBRANE_DEMO_DATA[0],timestamp:'2026-03-01',nonPermeateFlowNm3Hr:null},{...n.MEMBRANE_DEMO_DATA[0],timestamp:'2026-03-02',feedFlowNm3Hr:0}];const map={feedFlowNm3Hr:'q_feed',nonPermeateFlowNm3Hr:'q_non_perm',permeateFlowNm3Hr:'q_perm',permeateH2OnlinePct:'y_perm_h2_online',permeateH2LabPct:'y_perm_h2_lab',feedH2LabPct:'y_feed_h2_lab',feedH2OnlinePct:'y_feed_h2_online',feedPressureKpag:'p_feed_kpag'};const old=rows.map(r=>({timestamp:r.timestamp,...Object.fromEntries(Object.entries(map).map(([k,v])=>[v,r[k]]))}));const a=o.processBatch(old);const synth=n.synthesizeOnlineFeedH2(rows.map(r=>r.feedH2LabPct));const b=rows.map((r,i)=>n.calcMembraneRow({...r,feedH2OnlinePct:synth[i]}));for(let i=0;i<a.length;i++){eq(a[i].y_feed_h2_online,b[i].feedH2OnlinePct);eq(a[i].recOnline,b[i].recoveryOnlinePct);eq(a[i].recLab,b[i].recoveryLabPct);eq(a[i].ratio,b[i].ratio)}return `${rows.length} rows including deterministic synthetic feed and missing/zero flow.`});
test('Crude to Profit constants and full model across four process combinations',()=>{const s=read(orig+'crude-to-profit.html');const o=ctx(s.slice(s.indexOf('const CRUDES ='),s.indexOf('// ---- DOM helpers')));const n=ts(['crudeToProfit/data.ts','crudeToProfit/calculations.ts']);for(const k of Object.keys(n.DEFAULT_CRUDE_TO_PROFIT_CONFIG).filter(k=>k in o.DEFAULT_CONFIG && k!=="lpg_fuel_gas_recovered"))eq(o.DEFAULT_CONFIG[k],n.DEFAULT_CRUDE_TO_PROFIT_CONFIG[k],'config.'+k);eq(o.DEFAULT_CRUDE_FLOWS_M3HR,n.DEFAULT_CRUDE_FLOWS_M3HR,'flows');let cases=0;for(const f of [n.DEFAULT_CRUDE_FLOWS_M3HR,{OSH:0,SHD:0,AWB:0,SCO:0,FRB:0},{OSH:120,SHD:33,AWB:180,SCO:25,FRB:222}])for(const residue of ['lc_finer','delayed_coker'])for(const gas of ['hydrocracker','fcc']){const a=o.runModel(f,o.DEFAULT_CONFIG,null,null,residue,gas);const b=n.runModel(f,{...n.DEFAULT_CRUDE_TO_PROFIT_CONFIG,lpg_fuel_gas_recovered:1},null,null,residue,gas);eq(a,b,'model');cases++}return `${cases} complete model cases, including all output streams, byproducts and economics. No market fetch performed.`});
test('Furnace all bundled passes: P10/P50/P90 and threshold horizons',()=>{const s=read(orig+'furnace-skin-temp.html');const o=ctx('const ALARM_C=475,INTERNAL_HORIZON_DAYS=2555;'+['evalNode','predictModel','buildFeatureVector','forecastTC','forecastPass','statusFor'].map(n=>fn(s,n)).join('\n'));const n=ts(['furnace/calculations.ts']);const bundle=JSON.parse(read(root+'public/data/furnace-skin-temp-model.json'));let passes=0;const detail=[];const differences=[];let equalCentralSteps=0,unequalBandSteps=0;for(const f of Object.values(bundle.furnaces)){const state=Object.fromEntries(Object.entries(f.history.at(-1)).filter(([_k,v])=>typeof v==='number'));const by=Object.fromEntries(Object.keys(f.tc_models).map(k=>[k,f.history.map(r=>r[k]).filter(v=>v!=null)]));for(let p=1;p<=f.passes;p++){const a=o.forecastPass(f,p,state,f.history),b=n.forecastPass(f,p,state,by,bundle.alarm_threshold_c);if(!a||!b){eq(a,b);continue}for(const[k,v]of Object.entries({skinNowC:'skinNow',skin7dMeanC:'skin7dMean',skinVelocityCPerDay:'skinVel',hoursToAlarm:'hoursTo475',hoursToAlarmUpperBand:'hoursTo475UpperBand',extrapolatedDays:'extrapolatedDays'})){try{eq(a[v],b[k],k)}catch{differences.push({furnace:f.label,pass:p,field:k,original:a[v],react:b[k]})}}for(let i=0;i<a.forecast.length;i++){eq(a.forecast[i].value,b.forecast[i].value,'P50');equalCentralSteps++;if(Math.abs(a.forecast[i].p10-b.forecast[i].p10)>1e-9||Math.abs(a.forecast[i].p90-b.forecast[i].p90)>1e-9)unequalBandSteps++;}passes++;detail.push({furnace:f.label,pass:p,cadence:f.cadence_hours,current:b.skinNowC,hoursToAlarm:b.hoursToAlarm})}}for(const t of [459,460,469,470,475])eq(o.statusFor(t,null),n.statusForSkin(t,null));return {passes,daysPerPass:2555,equalCentralSteps,unequalBandSteps,differences,detail,restoredOutput:'Per-step drivenBy thermocouple identity is included in TS results'};});
const output={revision:'audit-remediation',method:'Original pure functions extracted directly and compared with TypeScript using Node stripping/VM. Relative/absolute tolerance 1e-9. Full published heater/exchanger/membrane rows plus edge cases, twelve economics cases and all nine furnace passes. Blower comparison covers representative pure-function inputs. This is not a complete equivalence proof.',results,comparisons:checks};
fs.writeFileSync(new URL('./engine-parity-results.json',import.meta.url),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));if(results.some(r=>r.status!=='PASS'||r.detail?.differences?.length))process.exitCode=1;
